markdown: redcarpet
pygments: true
permalink: /docs/:version/:resource
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]